export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_ALL_USERS = "DELETE_ALL_USERS";
export const RETRIEVE_ALL_USER = "RETRIEVE_ALL_USER";
export const RETRIEVE_DELETED_USERS = "RETRIEVE_DELETED_USERS";